<?php 
return [
    'Banda', 'Bandas', 'Band', 'Bands',
    'Grupo', 'Grupos', 'Group', 'Groups',
    'Orquestra', 'Orquestras', 'Orchestra', 'Orchestras',
    'Coletivo', 'Coletivos', 'Collective', 'Collectives',
    'Companhia', 'Companhias', 'Company', 'Companies',
    'Trupe', 'Trupes', 'Troupe', 'Troupes', 'trup',
    'Conjunto', 'Conjuntos', 'Ensemble', 'Ensembles',
    'Coral', 'Corais', 'Choir', 'Choirs',
    'Quinteto', 'Quintetos', 'Quintet', 'Quintets',
    'Quarteto', 'Quartetos', 'Quartet', 'Quartets',
    'Trio', 'Trios', 'Trio', 'Trios',
    'Dupla', 'Duplas', 'Duo', 'Duos',
    'Elenco', 'Elencos', 'Cast', 'Casts',
    'Núcleo', 'Núcleos', 'Nucleus', 'Nuclei',
    'Associação', 'Associações', 'Association', 'Associations',
    'Cooperativa', 'Cooperativas', 'Cooperative', 'Cooperatives',
    'Federação', 'Federações', 'Federation', 'Federations',
    'Instituto', 'Institutos', 'Institute', 'Institutes',
    'Fundação', 'Fundações', 'Foundation', 'Foundations',
    'Aliança', 'Alianças', 'Alliance', 'Alliances',
    'Consórcio', 'Consórcios', 'Consortium', 'Consortiums',
    'Sindicato', 'Sindicatos', 'Union', 'Unions',
    'Grêmio', 'Grêmios', 'Guild', 'Guilds',
    'Liga', 'Ligas', 'League', 'Leagues',
    'Confederação', 'Confederações', 'Confederation', 'Confederations',
    'Empresa', 'Empresas', 'Company', 'Companies',
    'Corporação', 'Corporações', 'Corporation', 'Corporations',
    'Holding', 'Holdings', 'Holding', 'Holdings',
    'Startup', 'Startups', 'Startup', 'Startups',
    'Negócio', 'Negócios', 'Business', 'Businesses',
    'Sociedade', 'Sociedades', 'Society', 'Societies',
    'Franquia', 'Franquias', 'Franchise', 'Franchises',
    'Conglomerado', 'Conglomerados', 'Conglomerate', 'Conglomerates',
    'Multinacional', 'Multinacionais', 'Multinational', 'Multinationals',
    'Comunidade', 'Comunidades', 'Community', 'Communities',
    'Coletivo', 'Coletivos', 'Collective', 'Collectives',
    'Coletividade', 'Coletividades', 'Collectivity', 'Collectivities',
    'Assembleia', 'Assembleias', 'Assembly', 'Assemblies',
    'Comitê', 'Comitês', 'Committee', 'Committees',
    'Conselho', 'Conselhos', 'Council', 'Councils',
    'Movimento', 'Movimentos', 'Movement', 'Movements',
    'Rede', 'Redes', 'Network', 'Networks',
    'Agremiação', 'Agremiações', 'Association', 'Associations',
    'Clube', 'Clubes', 'Club', 'Clubs',
    'Equipe', 'Equipes', 'Team', 'Teams',
    'Time', 'Times', 'Team', 'Teams',
    'Seleção', 'Seleções', 'Selection', 'Selections',
    'Panelinha', 'Panelinhas', 'Clique', 'Cliques',
    'Turma', 'Turmas', 'Group', 'Groups',
    'Galera', 'Galerias', 'Crew', 'Crews',
    'Staff', 'Staffs', 'Staff', 'Staffs',
    'Produção', 'Produções', 'Production', 'Productions',
    'Organização', 'Organizações', 'Organization', 'Organizations',
    'Agência', 'Agências', 'Agency', 'Agencies',
    'Música', 'Músicas', 'Music', 'Musics',
    'Fotografia', 'Fotografias', 'Photography', 'Photographies',
    'Entretenimento', 'Entretenimentos', 'Entertainment', 'Entertainments',
    'Cinema', 'Cinemas', 'Cinema', 'Cinemas',
    'Sala', 'Salas', 'Room', 'Rooms',
    'Museu', 'Museus', 'Museum', 'Museums',
    'Teatro', 'Teatros', 'Theater', 'Theaters', 'Teatral',
    'Galeria', 'Galerias', 'Gallery', 'Galleries',
    'Estúdio', 'Estúdios', 'Studio', 'Studios',
    'Editora', 'Editoras', 'Publisher', 'Publishers',
    'Livraria', 'Livrarias', 'Bookstore', 'Bookstores',
    'Festival', 'Festivais', 'Festival', 'Festivals',
    'Evento', 'Eventos', 'Event', 'Events',
    'Projeto', 'Projetos', 'Project', 'Projects',
    'LTDA', 'Ltd.',
    'Inc.',
    'EIRELI', 'Single-Member LLC',
    'ONG', 'ONGs', 'NGO', 'NGOs',
    'Filme', 'Filmes', 'Film', 'Films',
    'Série', 'Séries', 'Series', 'Series',
    'Podcast', 'Podcasts', 'Podcast', 'Podcasts',
    'Canal', 'Canais', 'Channel', 'Channels',
    'Revista', 'Revistas', 'Magazine', 'Magazines',
    'Jornal', 'Jornais', 'Newspaper', 'Newspapers',
    'Blog', 'Blogs', 'Blog', 'Blogs',
    'Auditório', 'Auditórios', 'Auditorium', 'Auditoriums',
    'Arena', 'Arenas', 'Arena', 'Arenas',
    'Centro Cultural', 'Centros Culturais', 'Cultural Center', 'Cultural Centers',
    'Espaço', 'Espaços', 'Space', 'Spaces',
    'Loja', 'Lojas', 'Store', 'Stores',
    'Restaurante', 'Restaurantes', 'Restaurant', 'Restaurants',
    'Café', 'Cafés', 'Café', 'Cafés',
    'Consultoria', 'Consultorias', 'Consulting', 'Consulting Services',
    'Design', 'Designs', 'Design', 'Designs',
    'Marketing', 'Marketing',
    'Publicidade', 'Publicidades', 'Advertising',
    'Hub', 'Hubs', 'Hub', 'Hubs',
    'Lab', 'Labs', 'Lab', 'Labs',
    'Platform', 'Platforms', 'Platform', 'Platforms',
    'Solutions', 'Solutions',
    'Ventures', 'Ventures',

    // religiões
    'Igreja', 'Igrejas',
    'Capela',
    'Catedral', 'Catedrais',
    'Basílica', 'Basílicas',
    'Paróquia', 'Paróquias',
    'Convento', 'Conventos',
    'Mosteiro', 'Mosteiros',
    'Santuário', 'Santuários',
    'Templo', 'Templos',
    'Missão', 'Missões',
    'Terreiro', 'Terreiros',
    'Ilê', 'Ilês',
    'Roça', 'Roças',
    'Axé', 'Axés',
    'Centro', 'Centros',
    'Tenda', 'Tendas',
    'Barracão', 'Barracões',
    'Mesquitas',
    'Sinagoga', 'Sinagogas',
    'Budista', 'Budistas',
    'Pagode', 'Pagodes',
    'Ashram', 'Ashrams',
    'Gurdwara', 'Gurdwaras',
    'Casa de Santo', 'Casas de Santo',
    'Casa de Culto', 'Casas de Culto',
    'Sagrário', 'Sagrários',
    'Altar', 'Altares',
    'Oratório', 'Oratórios',
    'Sede Religiosa', 'Sedes Religiosas',
    'Comunidade de Fé', 'Comunidades de Fé',

    // outras
    'bloco', 'carnaval', 'festejo', 
    'boi', 
    'noite', 'dia', 'junina', 'quadrilha',
    'ideia', 'ideias',
    'macumba', 'candomblé', 'umbanda',
    'mulher', 'mulheres', 'feminino', 'feminina', 'rapariga',
    'quilombo', 'quilombola', 'quilombar',
    'cultura', 'culturas', 'cultural', 'culturais',
    'concreto', 'vaso', 'vasos', 'cerâmica', 
    'arte', 'artes', 'artesanal',
    'realeza', 'realezas',
    'mazurca',
    'cia', 'circo', 'feira', 'feirinha', 'balé', 'grupo',
    'capoeira',
    'urbana',  'rural', 'periferia', 'periférica', 'favela', 
    'elite', 
    'mostra',
    'errante', 'itinerante',
    'máquina', 'criativo', 'criativa',
    'casa', 'casinha', 
    'ocitocina',
    'mamulengo',
    'praia',
    'frevo', 'maracatu', 'samba', 'forró', 'mpb', 'rock', 'batuque', 'pagode', 'coco', 'afoxe', 
    'superintendencia',
    'after', 'show', 'batalhão',
    'carnavalesca',
    'oficial', 'official', 'roots', 'dataprev', 'validador', 'secretaria', 'folia',
    'mundo',
    'vinil',
    'troca',
    'as', 'os',
    'escolinha', 'escola', 'academia',
    'camerata',
    'Sertão',
    'comunicacional',
    'cineclube',
    'setor', 'setorial',
    'educação', 'educacional',
    'premium', 'ouro',
    'paixao de cristo',
    'secult', 

    // universidades
    'UnB',
    'UFGD',
    'UFG',
    'UFMT',
    'UFMS',
    'UFCAT',
    'UFJ',
    'UFR',
    'UFBA',
    'UFSB',
    'UFRB',
    'UNILAB',
    'UFPB',
    'UFCA',
    'UFAL',
    'UFCG',
    'UFPE',
    'UFS',
    'UFC',
    'UFMA',
    'UFOB',
    'UFPI',
    'UFRN',
    'UNIVASF',
    'UFRPE',
    'UFERSA',
    'UNIR',
    'UFRR',
    'UFAC',
    'UNIFAP',
    'UFAM',
    'UFOPA',
    'UFPA',
    'UFT',
    'UFRA',
    'UNIFESSPA',
    'UNIFAL-MG',
    'UNIFEI',
    'UFJF',
    'UFLA',
    'UFMG',
    'UFOP',
    'UFSCar',
    'UFSJ',
    'UNIFESP',
    'UFU',
    'UFV',
    'UFABC',
    'UFES',
    'UNIRIO',
    'UFRJ',
    'UFTM',
    'UFVJM',
    'UFF',
    'UFRRJ',
    'UTFPR',
    'UFFS',
    'UNILA',
    'UFCSPA',
    'UFPel',
    'UFSC',
    'UFSM',
    'UNIPAMPA',
    'UFPR',
    'FURG',
    'UFRGS',
    'UFAPE',
    'UFDPar',
    'UFNT', 


    // retirada dos tipos de projetos
    'Ciclo',
    'Congresso',
    'Convenção',
    'Concurso',
    'Conferência',
    'Pública',
    'Setorial',
    'Nacional',
    'Estadual',
    'Consulta',
    'Municipal',
    'Curso',
    'Edital',
    'Encontro',
    'Exposição',
    'Exibição',
    'Feira',
    'Festival',
    'Festa',
    'Popular',
    'Religiosa',
    'Fórum',
    'Inscrições',
    'Intercâmbio',
    'Cultural',
    'Jornada',
    'Mostra',
    'Oficina',
    'Palestra',
    'Parada',
    'Desfile',
    'Militar',
    'Cívico',
    'Festivo',
    'Político',
    'Ações',
    'Afirmativas',
    'Pesquisa',
    'Programa',
    'Reunião',
    'Sarau',
    'Seminário',
    'Simpósio',
];
